# Generated by Django 5.1.3 on 2024-11-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
