# Generated by Django 5.1.3 on 2024-11-21 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_articles_text_alter_articles_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Advantage',
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
    ]
