# Generated by Django 5.1.3 on 2024-11-21 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_articles_advantage_alter_advantage_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advantage',
            new_name='Articles',
        ),
    ]
