# Generated by Django 5.1.3 on 2024-11-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_advantage_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Advantage',
        ),
    ]
