# Generated by Django 5.1.3 on 2024-12-04 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_advantage_likes_advantage_users_who_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advantage',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='advantage',
            name='users_who_liked',
        ),
    ]
